// word list reducer
export const ADD_WORD_BY_CHECKBOX = 'ADD_WORD_BY_CHECKBOX'
export const REMOVE_WORD = 'REMOVE_WORD'

export const ADD_SUBCATEGORY_BY_CHECKBOX = 'ADD_SUBCATEGORY_BY_CHECKBOX'
export const REMOVE_SUBCATEGORY_BY_CHECKBOX = 'REMOVE_SUBCATEGORY_BY_CHECKBOX'

export const ADD_NEW_WORD = 'ADD_NEW_WORD'

export const REPLACE_WORD_LIST = 'REPLACE_WORD_LIST'
export const RESET_LISTS = 'RESET_LISTS'

// save word list reducer
export const SAVE_WORD_LIST_REQUEST = 'SAVE_WORD_LIST_REQUEST'
export const SAVE_WORD_LIST_SUCCESS = 'SAVE_WORD_LIST_SUCCESS'
export const SAVE_WORD_LIST_FAIL = 'SAVE_WORD_LIST_FAIL'
export const SAVE_WORD_LIST_RESET = 'SAVE_WORD_LIST_RESET'

// get all saved word lists of user
export const SAVED_WORD_LISTS_REQUEST = 'SAVED_WORD_LISTS_REQUEST'
export const SAVED_WORD_LISTS_SUCCESS = 'SAVED_WORD_LISTS_SUCCESS'
export const SAVED_WORD_LISTS_FAIL = 'SAVED_WORD_LISTS_FAIL'

// delete word list
export const DELETE_WORD_LIST_REQUEST = 'DELETE_WORD_LIST_REQUEST'
export const DELETE_WORD_LIST_SUCCESS = 'DELETE_WORD_LIST_SUCCESS'
export const DELETE_WORD_LIST_FAIL = 'DELETE_WORD_LIST_FAIL'

export const GET_SAVED_LIST_REQUEST = 'GET_SAVED_LIST_REQUEST'
export const GET_SAVED_LIST_SUCCESS = 'GET_SAVED_LIST_SUCCESS'
export const GET_SAVED_LIST_FAIL = 'GET_SAVED_LIST_FAIL'
