// word list reducer
export const ADD_WORD_BY_CHECKBOX = 'ADD_WORD_BY_CHECKBOX'
export const REMOVE_WORD = 'REMOVE_WORD'

export const ADD_SUBCATEGORY_BY_CHECKBOX = 'ADD_SUBCATEGORY_BY_CHECKBOX'
export const REMOVE_SUBCATEGORY_BY_CHECKBOX = 'REMOVE_SUBCATEGORY_BY_CHECKBOX'

export const ADD_NEW_WORD = 'ADD_NEW_WORD'

// save word list reducer
export const SAVE_WORD_LIST_REQUEST = 'SAVE_WORD_LIST_REQUEST'
export const SAVE_WORD_LIST_SUCCESS = 'SAVE_WORD_LIST_SUCCESS'
export const SAVE_WORD_LIST_FAIL = 'SAVE_WORD_LIST_FAIL'

// get all saved word lists of user
export const SAVED_WORD_LISTS_REQUEST = 'SAVED_WORD_LISTS_REQUEST'
export const SAVED_WORD_LISTS_SUCCESS = 'SAVED_WORD_LISTS_SUCCESS'
export const SAVED_WORD_LISTS_FAIL = 'SAVED_WORD_LISTS_FAIL'

// delete word list
export const DELETE_WORD_LIST_REQUEST = 'DELETE_WORD_LIST_REQUEST'
export const DELETE_WORD_LIST_SUCCESS = 'DELETE_WORD_LIST_SUCCESS'
export const DELETE_WORD_LIST_FAIL = 'DELETE_WORD_LIST_FAIL'
