// word list reducer
export const ADD_WORD_BY_CHECKBOX = 'ADD_WORD_BY_CHECKBOX'
export const REMOVE_WORD = 'REMOVE_WORD'

export const ADD_SUBCATEGORY_BY_CHECKBOX = 'ADD_SUBCATEGORY_BY_CHECKBOX'
export const REMOVE_SUBCATEGORY_BY_CHECKBOX = 'REMOVE_SUBCATEGORY_BY_CHECKBOX'

export const ADD_NEW_WORD = 'ADD_NEW_WORD'

// save word list reducer
export const SAVE_WORD_LIST_REQUEST = 'SAVE_WORD_LIST_REQUEST'
export const SAVE_WORD_LIST_SUCCESS = 'SAVE_WORD_LIST_SUCCESS'
export const SAVE_WORD_LIST_FAIL = 'SAVE_WORD_LIST_FAIL'
